# Python Course / AI CLUB / Syrian Computer Society

## Numpy

### numpy is a library for scientific computing

In [2]:
import numpy as np

In [2]:
x=np.array([0,1,2,3,4,5])
print(x)
print(type(x))

[0 1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
y=np.array([0,1.2,2,3,4.8,5])
print(y)
print(type(y))

[0.  1.2 2.  3.  4.8 5. ]
<class 'numpy.ndarray'>


In [4]:
print(y.dtype)

float64


In [5]:
print(y.size)

6


In [6]:
y1=np.array([])
print(y1.ndim)

1


In [7]:
print(y.shape)

(6,)


In [8]:
z=np.array([5,6,8])
print(z.dtype)

int32


## indexing and slicing methods

In [16]:
a=np.array([1,2,3,4,5,6])
a[0]=0
print(a)

[0 2 3 4 5 6]


In [17]:
b=np.array([0,1,2,3,4,5])
print(b[0:4])

[0 1 2 3]


In [18]:
b[0:4]=[1,1,1,1]
print(b)

[1 1 1 1 4 5]


## Basic Operations

## vectors

In [20]:
u1=np.array([1,1,2])
v1=np.array([1,2,3])
z=u1+v1
print(z)

[2 3 5]


In [21]:
u1=np.array([1,1,2])
v1=np.array([1,2,3])
z=u1-v1
print(z)

[ 0 -1 -1]


## multiplication with a scalar value

In [22]:
a=np.array([1,2,1])
b=2*a
print(b)

[2 4 2]


## dot product

In [24]:
u=np.array([1,2,0])
v=np.array([0,1,0])
dot_p=np.dot(u,v)
print(dot_p)

2


In [3]:
a=np.array([[1,1,-1],[5,2,2],[3,3,0]])
print(a)

[[ 1  1 -1]
 [ 5  2  2]
 [ 3  3  0]]


In [4]:
print(a.dtype)

int32


In [5]:
print(a.size)

9


In [6]:
print(a.ndim)

2


In [7]:
print(a.shape)

(3, 3)


In [8]:
b=np.array([[0,1,2,5],[1,2,0,3],[1,1,4,0]])
print(b)

[[0 1 2 5]
 [1 2 0 3]
 [1 1 4 0]]


In [9]:
s=b[1:3,2]
print(s)

[0 4]


In [11]:
g=np.array([[1,2],[4,1]])
h=np.array([[4,6],[3,2]])
z=np.dot(g,h)
print(z)

[[10 10]
 [19 26]]


In [13]:
x=np.array([1,5,3])
print(x.max())
print(x.mean())

5
3.0
